version: '3.7'
services:
  mongo-db:
    image: mongo
    ports:
      - '27017:27017'
  server:
    build: backend
    image: sanjaysaini2000/meanstack_backend
    ports:
      - '8080:8080'
    links:
      - mongo-db
  client:
    build: frontend
    image: sanjaysaini2000/meanstack_frontend
    ports:
      - '4200:4200'